config/routes.rb
OfficeDrinkRounds::Application.routes.draw do

  resources :user_groups, path: 'groups' do
    resources :invites do
      get 'new_user'
      post 'create_user'
    end
    resources :rounds
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions

  resources :users

  root to: 'welcome#index'

  mount Rack::GitSha => '/sha'

end

app/models/invite.rb
class Invite < ActiveRecord::Base
  extend FriendlyId
  friendly_id :token

  attr_accessible :email

  validates :email, presence: true, email: true

  belongs_to :inviter, class_name: 'user'
  belongs_to :user_group

  before_save :generate_token

  def expired?
    created_at < 2.days.ago
  end

  def deliver_invite_email
    UserMailer.invite(self).deliver
  end

  private

  def generate_token
    self.token = SecureRandom.uuid if self.token.blank?
  end
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :user
  belongs_to :user_group

  attr_accessible :user, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation 

  validates :email, presence: true, uniqueness: true, email: true

  belongs_to :user_group

  has_many :invites, foreign_key: :inviter_id
  has_many :rounds
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  attr_accessible :name

  validates_presence_of :name

  has_many :users
  has_many :invites
  has_many :rounds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

  before_filter :find_user_group
  before_filter :find_invite, except: [:new, :create]

  def show
    # This is to stop invites being accessed by ID. Only the token is allowed.
    if request.path != user_group_invite_path(@user_group, @invite)
      redirect_to @user_group, alert: "Invite not found"
    end
  end

  def new
    @invite = @user_group.invites.new
  end

  def create
    @invite = @user_group.invites.build(params[:invite])

    if @invite.save
      redirect_to root_url, notice: 'Invite sent successfully'
    else
      render 'new'
    end
  end

  def new_user
    @user = @user_group.users.new(email: @invite.email)
  end

  def create_user
    @user = @user_group.users.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user_group, notice: 'Thanks for signing up!'
    else
      render 'new_user'
    end
  end

private

  def find_user_group
    @user_group = UserGroup.find(params[:user_group_id])
  end

  def find_invite
    @invite = @user_group.invites.find(params[:invite_id] || params[:id])
    if @invite.expired?
      redirect_to @user_group, alert: "Invite has expired"
    end
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

  before_filter :find_user_group

  def new
    @round = @user_group.rounds.new(user: current_user) 
  end

  def create
    @round = @user_group.rounds.new(params[:round])
    @round.user = current_user

    if @round.save
      redirect_to @user_group, notice: 'Round created'
    else
      render 'new'
    end
  end

private

  def find_user_group
    @user_group = UserGroup.find(params[:user_group_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'You logged in. Grats.'
    else
      flash.now.alert = 'Email or password incorrect'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out, yo'
  end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_filter :find_user_group, except: [:new, :create]

  def show
  end

  def new
    @user_group = UserGroup.new
  end

  def create
    @user_group = UserGroup.new params[:user_group]
    if @user_group.save
      redirect_to @user_group, notice: 'User group created'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user_group.update_attributes params[:user_group]
      redirect_to @user_group, notice: 'User group updated'
    else
      render 'edit'
    end
  end

private

  def find_user_group
    @user_group = UserGroup.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thanks for signing up!'
    else
      render 'new'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/invites/new.html.erb
<%= form_for @invite, url: user_group_invites_path(@user_group) do |f| %>
  <% if @invite.errors.any? %>
    <div class="errors">
      <h2>There be errors!</h2>
      <ul>
        <% @invite.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invites/new_user.html.erb
<h1>Sign up</h1>

<%= form_for @user, url: user_group_invite_create_user_path(@user_group, @invite) do |f| %>
  <% if @user.errors.any? %>
    <div class="errors">
      <h2>There be errors!</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invites/show.html.erb
showing invite for email - <%= @invite.email %>

<%= link_to 'Create account', user_group_invite_new_user_path(@user_group, @invite) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OfficeDrinkRounds</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="authentication">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to 'Log out', logout_path %>
  <% else %>
    <%= link_to 'Log in', login_path %> or
    <%= link_to 'Sign up', signup_path %>
  <% end %>
</div>

<% flash.each do |name, message| %>
  <%= content_tag :div, message, class: "flash #{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/rounds/new.html.erb
<%= form_for @round, url: user_group_rounds_path(@user_group) do |f| %>
  <%= f.submit %>
<% end %>

app/views/user_groups/_form.html.erb
<%= form_for @user_group do |f| %>
  <% if @user_group.errors.any? %>
    <div class="errors">
      <h2>There be errors!</h2>
      <ul>
        <% @user_group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Edit user group</h1>

<%= render 'user_groups/form' %>

app/views/user_groups/new.html.erb
<h1>New user group</h1>

<%= render 'user_groups/form' %>

app/views/user_groups/show.html.erb
<h1><%= @user_group.name %></h1>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="errors">
      <h2>There be errors!</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>